# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trainer-config
  labels:
    app: trainer
data:
  general-config.yaml: |-
    {{ .Files.Get "general-config.yaml" | nindent 4 }}
  trainer-config.yaml: |-
    {{ .Files.Get "trainer-config.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: detector-config
  labels:
    app: detector
data:
  detector-—Åonfig.yaml: |-
    {{ .Files.Get "detector-config.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maintainer-config
  labels:
    app: maintainer
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  general-config.yaml: |-
    {{ .Files.Get "general-config.yaml" | nindent 4 }}