apiVersion: v1
kind: ConfigMap
metadata:
  name: mad-trainer-config
  labels:
    app: mad-trainer
data:
  config.yaml: |
    general:
      victoriametrics_url: {{ .Values.general.victoriametrics_url | quote }}
      db_conn_string: {{ .Values.general.db_conn_string | quote }}
      log_path: {{ .Values.general.log_path | quote }}

      metrics:
        {{- toYaml .Values.general.metrics | nindent 8 }}

      models:
        {{- toYaml .Values.general.models | nindent 8 }}

    mad-components:
      mad-trainer:
        optuna_tuning:
          {{- toYaml .Values.mad-components.mad-trainer.optuna_tuning | nindent 12 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mad-detector-config
  labels:
    app: mad-detector
data:
  config.yaml: |
    # Настройки детектора
    mad-components:
      mad-detector:
        {{- $detector := .Values.mad-components.mad-detector }}
        points_anomaly: {{ $detector.points_anomaly | toYaml | nindent 8 }}
        system_anomaly:
          percentile_threshold: {{ $detector.system_anomaly.percentile_threshold }}
          min_confirmations: {{ $detector.system_anomaly.min_confirmations | toYaml | nindent 10 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mad-maintainer-config
  labels:
    app: mad-maintainer
data:
  config.yaml: |
    # Основные настройки
    general:
      # Настройки подключения
      db_conn_string: {{ .Values.general.db_conn_string | quote }}
      log_path: {{ .Values.general.log_path | quote }}
      
      # Метрики
      metrics:
        {{- range .Values.general.metrics }}
        - {{ merge (dict "interpolation" "linear") . | toYaml | nindent 8 | trim }}
        {{- end }}

      # Модели
      models:
        {{- range .Values.general.models }}
        - {{ merge (dict 
            "version_history" 3 
            "hyperparameter_mode" "optuna"
            "retrain" (dict "enabled" true)
          ) . | toYaml | nindent 8 | trim }}
        {{- end }}

    # Настройки детектора
    mad-components:
      mad-detector:
        {{- $detector := .Values.mad-components.mad-detector }}
        points_anomaly: {{ $detector.points_anomaly | toYaml | nindent 8 }}
        system_anomaly:
          percentile_threshold: {{ $detector.system_anomaly.percentile_threshold }}
          min_confirmations: {{ $detector.system_anomaly.min_confirmations | toYaml | nindent 10 }}
