apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad
      component: api
  template:
    metadata:
      labels:
        app: mad
        component: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.mad-components.mad-api.image.repository }}:{{ .Values.mad-components.mad-api.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: DB_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: mad-secrets
              key: db-conn-string
        - name: TRAINER_SERVICE_URL
          value: {{- include "serviceFQDN" (dict "name" "mad-api") | nindent 10 }}
        - name: LOG_PATH
          value: {{ .Values.general.log_path }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad
      component: detector
  template:
    metadata:
      labels:
        app: mad
        component: detector
    spec:
      containers:
        - name: detector
          image: "{{ .Values.mad-components.mad-detector.image.repository }}:{{ .Values.mad-components.mad-detector.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: mad-secrets
                  key: db-conn-string
            - name: VICTORIAMETRICS_URL
              value: {{ .Values.general.victoriametrics_url }}
            - name: NOTIFIER_SERVICE_URL
              value: {{- include "serviceFQDN" (dict "name" "mad-notifier") | nindent 10 }}
            - name: LOG_PATH
              value: {{ .Values.general.log_path }}
          volumeMounts:
            - mountPath: /app/config
              name: config
    restartPolicy: OnFailure
    volumes:
      - name: config
        configMap:
          name: mad-detector-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad
      component: notifier
  template:
    metadata:
      labels:
        app: mad
        component: notifier
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mad-components.mad-notifier.image.repository }}:{{ .Values.mad-components.mad-notifier.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mad-components.mad-notifier.service.port }}
              protocol: {{ .Values.mad-components.mad-notifier.service.protocol }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-telegram-secrets
          env:
            - name: PORT
              value: {{ .Values.mad-components.mad-notifier.service.port }}
            - name: DEBUG
              value: {{ .Values.mad-components.mad-notifier.debug }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http