apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad
      component: api
  template:
    metadata:
      labels:
        app: mad
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.mad_components.mad_api.image.repository }}:{{ .Values.mad_components.mad_api.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.mad_components.mad_trainer.service.port | quote }}
          env:
            - name: DB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: mad-secrets
                  key: db-conn-string
            - name: TRAINER_SERVICE_URL
              value: {{ include "serviceFQDN" (merge (dict "name" "mad_api") .) }}
            - name: LOG_PATH
              value: {{ .Values.general.log_path }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad
      component: trainer
  template:
    metadata:
      labels:
        app: mad
        component: trainer
    spec:
      containers:
      - name: trainer
        image: "{{ .Values.mad_components.mad_trainer.image.repository }}:{{ .Values.mad_components.mad_trainer.image.tag }}"
        ports:
          - name: http
            containerPort: {{ .Values.mad_components.mad_trainer.service.port | quote }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-db-secret
          - secretRef:
              name: {{ .Release.Name }}-vm
        env:
          - name: GENERAL_CONFIG_PATH
            value: /app/config/general-config.yaml
          - name: TRAINER_CONFIG_PATH
            value: /app/config/trainer-config.yaml
          - name: LOG_PATH
            value: ./anomaly_detection.log
          - name: DETECTOR_SERVICE_URL
            value: {{ include "serviceFQDN" (merge (dict "name" "mad_detector") .) }}
        volumeMounts:
          - mountPath: /app/config
            name: config
      volumes:
        - name: config
          configMap:
            name: trainer-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad
      component: detector
  template:
    metadata:
      labels:
        app: mad
        component: detector
    spec:
      containers:
        - name: detector
          image: "{{ .Values.mad_components.mad_detector.image.repository }}:{{ .Values.mad_components.mad_detector.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.mad_components.mad_detector.service.port | quote }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-db-secret
            - secretRef:
                name: {{ .Release.Name }}-vm
          env:
            - name: NOTIFIER_SERVICE_URL
              value: {{ include "serviceFQDN" (merge (dict "name" "mad_notifier") .) }}
            - name: LOG_PATH
              value: {{ .Values.general.log_path }}
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - name: config
          configMap:
            name: detector-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad
      component: notifier
  template:
    metadata:
      labels:
        app: mad
        component: notifier
    spec:
      containers:
        - name: notifier
          image: "{{ .Values.mad_components.mad_notifier.image.repository }}:{{ .Values.mad_components.mad_notifier.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.mad_components.mad_notifier.service.port | quote }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-telegram-secrets
          env:
            - name: PORT
              value: {{ .Values.mad_components.mad_notifier.service.port | quote }}
            - name: DEBUG
              value: {{ .Values.mad_components.mad_notifier.debug }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
