apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  DB_CONN_STRING: {{ .Values.general.db_conn_string | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-telegram-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
{{- if .Values.notifier.bot_token }}
  TELEGRAM_BOT_TOKEN: {{ .Values.notifier.bot_token | b64enc | quote }}
{{- end }}
{{- if .Values.notifier.chat_id }}
  TELEGRAM_CHAT_ID: {{ .Values.notifier.chat_id | b64enc | quote }}
{{- end }}