apiVersion: v1
kind: Service
metadata:
  name: vmsingle-service
spec:
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 8428
      nodePort: 30429
  selector:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: stack
  type: NodePort
