{{- range $name, $config := .Values.mad-components }}
{{- if and $config.service (eq $config.service.type "NodePort") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-nodeport
  labels:
    app: {{ $name }}
spec:
  type: NodePort
  ports:
    - port: {{ $config.service.port | default $config.service.targetPort }}
      targetPort: {{ $config.service.targetPort }}
      protocol: {{ $config.service.protocol | default "TCP" }}
      {{- if $config.service.nodePort }}
      nodePort: {{ $config.service.nodePort }}
      {{- end }}
  selector:
    app: {{ $name }}
{{- end }}
{{- end }}