{{- range $name, $config := .Values.mad-components }}
{{- if $config.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: {{ $config.service.type }}
  ports:
    - port: {{ $config.service.port }}
      targetPort: {{ $config.service.targetPort }}
      protocol: {{ $config.service.protocol | default "TCP" }}
      {{- if and (eq $config.service.type "NodePort") $config.service.nodePort }}
      nodePort: {{ $config.service.nodePort }}
      {{- end }}
  selector:
    app: {{ $name }}
{{- end }}
{{- end }}