general:
  victoriametrics_url: ""
  db_conn_string: ""
  log_path: "./anomaly_detection.log" # LOG_PATH всем
  config_dir: "./config"
  pullPolicy: "Always"

mad_components:
  mad_api:
    image:
      repository: "vladaderina/mad-api"
      tag: "latest"
    service:
      type: NodePort
      port: 30001
      nodePort: 30001
      targetPort: 30001

  mad_scheduler:
    image:
      repository: "vladaderina/mad-scheduler"
      tag: "latest"
    service:
      type: ClusterIP
      port: 30002
      targetPort: 30002

  mad_maintainer:
    image:
      repository: "vladaderina/mad-maintainer"
      tag: "latest"
    service:
      type: ClusterIP
      port: 30003
      targetPort: 30003

  mad_trainer:
    image:
      repository: "vladaderina/mad-trainer"
      tag: "latest"
    service:
      type: ClusterIP
      port: 30004
      targetPort: 30004

  mad_detector:
    image:
      repository: "vladaderina/mad-detector"
      tag: "latest"
    service:
      type: ClusterIP
      port: 30005
      targetPort: 30005

  mad_notifier:
    image:
      repository: "vladaderina/mad-notifier"
      tag: "latest"
    service:
      type: ClusterIP
      port: 30006
      targetPort: 30006
    debug: true
    bot_token: ""
    chat_id: ""