system:
  log_path: "./anomaly_detection.log" # HELM
  alerting: true # HELM
  victoriametrics_url: "http://80.93.60.49:30429/api/v1"  # ПС
  db_conn_string: "postgresql://mad:secretPASSW0rd@80.93.60.49:30000/ml_models"  # ПС

metrics:
  - name: "requests_total" # БД
    query: 'vm_http_requests_total{path="/api/v1/query_range"}' # БД
    interpolation: "linear" # БД
    exclude_periods:
      - start: "2023-05-10T12:00:00Z" # БД
        end: "2023-05-10T14:30:00Z" # БД
        reason: "Технические работы" # БД
        anomaly_type: "global"
      - start: "2023-05-15T09:00:00Z" # БД
        end: "2023-05-15T11:45:00Z" # БД
        reason: "Сбой в системе" # БД
        anomaly_type: "local"
  - name: "cpu_utilization" # БД
    query: 'vm_http_requests_total{path="/api/v1"}' # БД

mad_predictor:
  # none
  optuna_tuning:
    direction: "minimize"
    metric: "val_loss"
    n_trials: 20
    sampler: "TPE"
    pruner: "Hyperband"
    hyperparameter_ranges:
      layers:
        - type: "LSTM"
          units:
            min: 32
            max: 256
            step: 32
          return_sequences: [True, False]
        - type: "Dense"
          units:
            min: 1
            max: 64
      learning_rate:
        min: 0.0001
        max: 0.01
        log: true
      batch_size: [16, 32, 64, 128]
      dropout:
        min: 0.1
        max: 0.5
      epochs:
        min: 10
        max: 100
    fixed_parameters:
      loss: "mean_squared_error"
      optimizer: "adam"
      validation_split: 0.2
  # none
  models:
    - name: "requests_total_hard" # БД
      main_metric: "requests_total" # БД
      additional_metrics:
        - "cpu_utilization"  # БД
      version_history: 5 # БД
      hyperparameter_mode: "optuna" # БД
      retrain:
        enabled: true # HELM
        strategy: "sliding_window" # HELM
        interval: "7d" # HELM
      training_period:
        fixed_range:
          start: "2025-07-18T07:28:03Z" # БД
          end: "2025-07-29T08:00:30Z" # БД
          step: "1m" # БД
  # none
    - name: "requests_total_easy"
      main_metric: "requests_total" # БД
      version_history: 1 # БД
      hyperparameter_mode: "manual" # БД
      # БД
      manual_params:
        layers:
          - type: "LSTM"
            units: 64
            return_sequences: True
          - type: "LSTM"
            units: 32
            return_sequences: False
          - type: "Dense"
            units: 1
        learning_rate: 0.001
        batch_size: 32
        dropout: 0.2
        epochs: 50
        loss: "mean_squared_error"
        optimizer: "adam"
        validation_split: 0.2
        window_size: 24
      # БД
      retrain:
        enabled: true # HELM
        strategy: "expanding_window" # HELM
        interval: "12h" # HELM
      training_period:
        auto_range:
          lookback_period: "8d" # none
          step: "1m" # none

mad_detector:
  points_anomaly:
    - query: requests_total # HELM
      delta_threshold: "auto" # HELM
    - query: requests_total_2 # HELM
      delta_threshold: 65 # HELM
  system_anomaly:
    percentile_threshold: 0.95 # none - params DB
    min_confirmations:
      group_anomaly: 20 # none - params DB
      local_anomaly: 3 # none - params DB
      global_anomaly: 1 # none - params DB

mad_notifier:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN" # ПС
  chat_id: "YOUR_TELEGRAM_CHAT_ID" # ПС
  message_template: "Обнаружена аномалия! Метрика: {metric}, Время: {timestamp}, Значение: {value}" # БД