---
# Network configuration
internal_network: "192.168.1.0/24"
admin_ips: 
  - "192.168.1.100/32"
  - "10.0.0.50/32"
vpn_network: "10.8.0.0/24"

# Service ports
ssh_port: 22
victoriametrics_port: 8428
grafana_port: 3000
postgresql_port: 5432
loki_port: 3100
k3s_api_port: 6443

# Service configuration
victoria_metrics_allowed_ips: "192.168.1.50/32"
enable_external_victoria_metrics: false
firewall_enabled: true
allowed_ips:
  - "94.181.45.153/32"

# Security settings
ssh_key_only: true
enable_fail2ban: true
enable_2fa: false
install_k3s: false

# Sysctl settings
sysctl_settings:
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.tcp_syncookies: 1
  net.ipv4.ip_forward: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  net.ipv4.icmp_ignore_bogus_error_responses: 1

# PostgreSQL configuration
postgresql_users:
  - name: grafana
    password: "{{ vault_grafana_db_password }}"
    databases: [grafana]
  - name: victoriametrics
    password: "{{ vault_vm_db_password }}"
    databases: [victoriametrics]

# VictoriaMetrics retention
vm_retention_period: 1

# Service ports and access rules
service_ports:
  - { port: 22, protocol: tcp, description: "SSH", allowed_ips: ["94.181.45.153/32"], state: "allow" }
  - { port: 80, protocol: tcp, description: "HTTP", allowed_ips: ["94.181.45.153/32"], state: "allow" }
  - { port: 443, protocol: tcp, description: "HTTPS", allowed_ips: ["94.181.45.153/32"], state: "allow" }
  - { port: "{{ grafana_port }}", protocol: tcp, description: "Grafana", allowed_ips: ["94.181.45.153/32"], state: "allow" }
  - { port: "{{ victoriametrics_port }}", protocol: tcp, description: "VictoriaMetrics", allowed_ips: ["127.0.0.1"], state: "allow" }
  - { port: "{{ loki_port }}", protocol: tcp, description: "Loki", allowed_ips: ["127.0.0.1"], state: "allow" }
  - { port: "{{ postgresql_port }}", protocol: tcp, description: "PostgreSQL", allowed_ips: ["127.0.0.1"], state: "allow" }