# mad-trainer-config.yaml
general:
  metrics:
    - name: "requests_total"
      query: 'vm_http_requests_total{path="/api/v1/query_range"}'
      interpolation: "linear"
      exclude_periods:
        - start: "2023-05-10T12:00:00Z"
          end: "2023-05-10T14:30:00Z"
          reason: "Технические работы"
          anomaly_type: "global"
        - start: "2023-05-15T09:00:00Z"
          end: "2023-05-15T11:45:00Z"
          reason: "Сбой в системе"
          anomaly_type: "local"
    - name: "cpu_utilization"
      query: 'vm_http_requests_total{path="/api/v1"}'

  models:
    - name: "requests_total_hard"
      main_metric: "requests_total"
      additional_metrics:
        - "cpu_utilization"
      version_history: 5
      hyperparameter_mode: "optuna"
      retrain:
        enabled: true
        strategy: "sliding_window"
        interval: "7d"
      training_period:
        fixed_range:
          start: "2025-07-18T07:28:03Z"
          end: "2025-07-29T08:00:30Z"
          step: "1m"
    - name: "requests_total_easy"
      main_metric: "requests_total"
      version_history: 1
      hyperparameter_mode: "manual"
      manual_params:
        layers:
          - type: "LSTM"
            units: 64
            return_sequences: True
          - type: "LSTM"
            units: 32
            return_sequences: False
          - type: "Dense"
            units: 1
        learning_rate: 0.001
        batch_size: 32
        dropout: 0.2
        epochs: 50
        loss: "mean_squared_error"
        optimizer: "adam"
        validation_split: 0.2
        window_size: 24
      retrain:
        enabled: true
        strategy: "expanding_window"
        interval: "12h"
      training_period:
        auto_range:
          lookback_period: "8d"
          step: "1m"