site_name: Metrics Anomaly Detection

docs_dir: mkdocs

site_url: https://vladaderina.github.io/MAD/

site_description: Документация по проекту Metrics Anomaly Detection

site_author: Vlada Derina

repo_url: https://github.com/vladaderina/MAD/tree/main

theme:
  name: material
  features:
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle

nav:
  - Описание проекта: index.md
  - Быстрый старт:
    - Системные требования: getting-started/requirements.md
    - Создание сервера: getting-started/terraform.md
    - Настройка сервера:
      - Сеть и доступы: getting-started/network.md
      - Установка инфраструктурного ПО:
        - На хост:
          - Ansible: getting-started/ansible.md
          - Ручная установка:
            - Установка minikube: getting-started/minikube.md
            - Установка k3s: getting-started/k3s.md
            - Установка остального ПО: getting-started/others_pp.md
        - В кластер k8s:
          - Приложение "E-commerce": getting-started/e-commerce-deploy.md
          - Хранилище: getting-started/storage.md
          - Система мониторинга: getting-started/monitoring.md
      - Настройка PostgreSQL: getting-started/mad_install.md
      - Установка MAD: getting-started/mad_install.md
    - Быстрый запуск: getting-started/quickstart.md
  - Архитектура:
      - Обзор: mad/overview.md
      - Конфигурация: mad/config.md
      - База данных: mad/data_base.md
      - Сервис сбора данных: mad/metrics_collection.md
      - Сервис обучения моделей: mad/model_training.md
      - Сервис предсказания аномалий: mad/anomaly_prediction.md
      - Сервис уведомлений: mad/notification.md
  - Мониторинг: 
    - Сбор метрик: 
      - Метрики kubernetes: control-plane-metrics.md
    - Сбор логов: 
      - Логи kubernetes: control-plane-metrics.md
      - Istio: istio.md
  - CI/CD: ci-cd.md
  - Архив:
    - Анализ аномалий: 
      - Сontrol plane: breakdown1.md
    - Теория:
      - Reverse engineering приложения "E-commerce": e-commerce-theory.md
      - Метрики: metrics.md
      - Основные метрики для мониторинга состояния кластера: metrics_types.md
      - Архитектура HA кластера: architecture.md
      - Компоненты control plane: cp.md
      - Автоматизированное развертывание K8s: k8s-deploy.md

extra_css:
  - css/extra.css

plugins:
  - search
  - table-reader
  - include-markdown
  - mermaid2
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - attr_list
    - def_list
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - attr_list
    - md_in_html
    - tables

copyright: Copyright &copy; 2024 <a href="https://t.me/vladaderina">Vlada Derina</a>.
