---
- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present

- name: Ensure PostgreSQL data directory exists
  file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Configure PostgreSQL listen addresses
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: "^listen_addresses"
    line: "listen_addresses = '{{ postgresql_listen_addresses }}'"
    backup: yes

- name: Configure PostgreSQL port
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: "^port"
    line: "port = {{ postgresql_port }}"
    backup: yes

- name: Configure pg_hba.conf for local access only
  copy:
    content: |
      # TYPE  DATABASE        USER            ADDRESS                 METHOD
      local   all             all                                     peer
      host    all             all             127.0.0.1/32            scram-sha-256
      host    all             all             ::1/128                 scram-sha-256
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    backup: yes

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted

- name: Change postgres user password
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "{{ vault_postgres_password | default('change_me_please') }}"
    encrypted: yes