name: Helm Deploy Pipeline

on:
  push:
    branches: 
      - main
    paths:
      - 'helm/mad/**'
  pull_request:
    branches:
      - main
    paths:
      - 'helm/mad/**'

env:
  HELM_CHART_DIR: helm/mad
  RELEASE_NAME: mad
  NAMESPACE: mad

jobs:
  lint-test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Helm
      run: helm version

    - name: Lint Helm chart
      run: helm lint $HELM_CHART_DIR

    - name: Template test (with secrets placeholder)
      run: |
        helm template $RELEASE_NAME $HELM_CHART_DIR \
          --namespace $NAMESPACE \
          --set general.victoriametrics_url="placeholder" \
          --set general.db_conn_string="placeholder" \
          --set mad_components.mad_notifier.bot_token="placeholder" \
          --set mad_components.mad_notifier.chat_id="placeholder"

  dry-run:
    runs-on: self-hosted
    needs: lint-test
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dry-run deployment (with placeholder secrets)
      run: |
        helm upgrade $RELEASE_NAME $HELM_CHART_DIR \
          --namespace $NAMESPACE \
          --install \
          --dry-run \
          --set general.victoriametrics_url="placeholder" \
          --set general.db_conn_string="placeholder" \
          --set mad_components.mad_notifier.bot_token="placeholder" \
          --set mad_components.mad_notifier.chat_id="placeholder"

  determine-deployment-type:
    runs-on: self-hosted
    needs: lint-test
    if: github.event_name == 'push'
    outputs:
      deployment_type: ${{ steps.detect-type.outputs.deployment_type }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect deployment type
      id: detect-type
      run: |
        if helm status $RELEASE_NAME --namespace $NAMESPACE >/dev/null 2>&1; then
          echo "deployment_type=upgrade" >> $GITHUB_OUTPUT
        else
          echo "deployment_type=install" >> $GITHUB_OUTPUT
        fi

    - name: Show changes (with placeholder secrets)
      run: |
        helm diff upgrade $RELEASE_NAME $HELM_CHART_DIR \
          --namespace $NAMESPACE \
          --allow-unreleased \
          --context 5 \
          --set general.victoriametrics_url="placeholder" \
          --set general.db_conn_string="placeholder" \
          --set mad_components.mad_notifier.bot_token="placeholder" \
          --set mad_components.mad_notifier.chat_id="placeholder"

  deploy:
    runs-on: self-hosted
    needs: determine-deployment-type
    if: github.event_name == 'push'
    environment: prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Helm chart with secrets
      run: |
        echo "Performing ${{ needs.determine-deployment-type.outputs.deployment_type }}"
        
        helm upgrade $RELEASE_NAME $HELM_CHART_DIR \
          --namespace $NAMESPACE \
          --install \
          --atomic \
          --timeout 5m \
          --create-namespace \
          --set general.victoriametrics_url="${{ secrets.VICTORIAMETRICS_URL }}" \
          --set general.db_conn_string="${{ secrets.DB_CONN_STRING }}" \
          --set mad_components.mad_notifier.bot_token="${{ secrets.BOT_TOKEN }}" \
          --set mad_components.mad_notifier.chat_id="${{ secrets.CHAT_ID }}"

    - name: Verify deployment
      run: |
        kubectl wait --for=condition=Ready pods --all -n $NAMESPACE --timeout=300s
        helm status $RELEASE_NAME --namespace $NAMESPACE